# SOTA Visualizer グループ化設定テンプレート
# SEが必要に応じてこのファイルをコピーして使用
# ファイル名: sota_grouping_config.yaml
#
# 注: 現在の"Hardware Level"は実際にはMiddleware Level（gcc, intel等）
# 真のHardware Level（single-node/multi-node）の比較が必要な場合は
# SEがプロジェクト要件に応じてカスタマイズしてください

# ハードウェアレベルのグループ化設定（実際はミドルウェアレベル）
hardware:
  # 自動検出方法を選択
  detection: "hardware_info"  # hardware_info.mdの位置で自動判定（デフォルト）
  # detection: "path_index"    # パスの特定位置でグループ化
  # detection: "manual"        # 手動マッピング
  
  # path_indexモードの場合
  path_index: 2  # Flow/TypeII/XXX のXXX部分（0から数える）
  
  # manualモードの場合のマッピング
  manual_groups:
    - name: "single-node"
      patterns: ["single-node", "1node", "single"]
    - name: "multi-node"
      patterns: ["multi-node", "multi", "distributed"]
    - name: "gpu-cluster"
      patterns: ["gpu", "cuda-cluster", "multi-gpu"]

# ファミリーレベルのグループ化設定
family:
  # 技術名の区切り文字
  separator: "_"  # OpenMP_MPI のような形式（デフォルト）
  
  # 世代判定ルール
  generation_rules:
    - generation: 1
      separator_count: 0  # OpenMP, MPI, CUDA
    - generation: 2
      separator_count: 1  # OpenMP_MPI, MPI_CUDA
    - generation: 3
      separator_count: 2  # OpenMP_MPI_AVX2
  
  # 明示的な親子関係（オプション）
  explicit_relationships:
    OpenMP_MPI:
      parents: [OpenMP, MPI]
      generation: 2
    OpenMP_MPI_AVX2:
      parents: [OpenMP_MPI, AVX2]
      generation: 3

# グラフ生成設定
visualization:
  # マイルストーン時刻（分）
  milestones: [30, 60, 90, 120, 180]
  
  # グラフスタイル
  style:
    line_width: 2.5
    marker_size: 6
    sota_line_style: "--"
    sota_line_alpha: 0.5
  
  # 出力設定
  output:
    dpi: 120
    format: "png"
    save_milestones: true  # マイルストーン時に別ディレクトリに保存