receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  attributes:
    actions:
      - key: service.name
        value: claude-code
        action: upsert
      - key: deployment.environment
        value: vibecodehpc
        action: insert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: vibecodehpc
    const_labels:
      project: "vibecodehpc"
  
  otlphttp:
    endpoint: http://loki:3100/otlp
    
  debug:
    verbosity: normal

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [prometheus, debug]
    
    logs:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [otlphttp, debug]